In [3]:
import numpy as np 
a= np.array([1,2,3,4,5])
b= np.array([3,4,4,6,7])
#addition
print(a+b)
#subtraciton
print(a-b)
#multiplication 
print(a*b)
#division
print(a/b)
#modulo 
print(a//b)
#exponential 
print(a**b)
#matrix multiplicationo 
c = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])
print(np.dot(c,d))
# trigonmetric function
trig = np.array([0,15,30,60])
#to use trigo function we need to convert this degree into radian 
trig1 = np.deg2rad(trig)
print("sin:" , np.sin(trig1))
print("cos:" , np.cos(trig1))
#logarithm function 
print(np.log(a))
print(np.log10(a))
#bitwise operations 
bit1= np.array([1,2,3,4] , dtype = np.uint8)
bit2= np.array([2,4,6,8] , dtype = np.uint8)
print("Bitwise and : " , np.bitwise_and(bit1, bit2))
print("Bitwise or: " , np.bitwise_or(bit1, bit2))






[ 4  6  7 10 12]
[-2 -2 -1 -2 -2]
[ 3  8 12 24 35]
[0.33333333 0.5        0.75       0.66666667 0.71428571]
[0 0 0 0 0]
[    1    16    81  4096 78125]
[[19 22]
 [43 50]]
sin: [0.         0.25881905 0.5        0.8660254 ]
cos: [1.         0.96592583 0.8660254  0.5       ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
Bitwise and :  [0 0 2 0]
Bitwise or:  [ 3  6  7 12]


In [4]:
##comparision operator
print(a==b)
print(a>b)
print(a<b)
print(a!=b)
print(a>=b)
print(a<=b)


[False False False False False]
[False False False False False]
[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]


In [5]:
##aggregation function 

#sum 
print(np.sum(a))
#mean 
print(np.mean(a))
#median 
print(np.median(a))
#standard deviation 
print(np.std(a))
#variance 
print(np.var(a))
#maximum
print(np.max(a))
#minimum
print(np.min(a))





15
3.0
3.0
1.4142135623730951
2.0
5
1


In [6]:
#sorting operation 
print(np.sort(b))

print("reverse order" ,np.sort(b)[::-1])

[3 4 4 6 7]
reverse order [7 6 4 4 3]
