# Reshaping , Spliting  ans  Stacking Of Arrays 

Reshaping is the process of converting a Numpy array into  a different shapes without changing its data
splitting is the process of dividing a numpy array into smaller arrays along one or more axes 
stacking is the process of combining two or more numpy arrays into a single array along a new axis 

In [1]:
import numpy as np 

In [8]:
#reshaping 
a = np.array([[1,2,4] ,[3,6,9]])
#to detemining the shape of the array that is no of rows and columns in 2d array 
b =a.shape
print("original shape :" ,b)
a.reshape(3,2)

original shape : (2, 3)


array([[1, 2],
       [4, 3],
       [6, 9]])

In [20]:
#splitting  
#axis is nothing but a direction where you want to split 
b,c = np.split(a ,2, axis=0)
print(b)
print(c)

[[1 2 4]]
[[3 6 9]]


In [23]:
# stacking 
a = np.array([1,2,4])
b= np.array([5,7,19])
c= np.vstack((a ,b))
d = np.hstack((a,b))
print(c)
print(d)

[[ 1  2  4]
 [ 5  7 19]]
[ 1  2  4  5  7 19]


In [25]:
#concate 
a = np.array([[1,2] ,[3,4]])
b = np.array([[5,6]])
c= np.concatenate((a,b) , axis = 0)
print(c)
d = np.concatenate((a,b) , axis = None)
print(d)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [26]:
#transpose
a

array([[1, 2],
       [3, 4]])

In [27]:
a.T

array([[1, 3],
       [2, 4]])

In [28]:
#ndims , nsize , nshape
a.size

4

In [29]:
a.ndim

2